services:
  web:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app/backend:/app/app/backend
      - ./run.py:/app/run.py
      - ./settings.json:/app/settings.json
    env_file:
      - .env
    environment:
      - PYNGROK_CONFIG=/home/app/.config/ngrok/ngrok.yml

  frontend:
    build:
      context: ./app/frontend
      docke