services:
  web:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app/backend:/app/app/backend
      - ./run.py:/app/run.py
      - ./settings.json:/app/settings.json
    env_file:
      - .env
    command: gunicorn --bind 0.0.0.0:5000 --worker-class=gthread --workers=2 --preload "run:app"

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - web